### PR TITLE
fix error in first proof, and minor typo further down

### PR DESCRIPTION
**Pull request by jimevart**

### CODE REVIEW

**Comment by jimevart** [comment]
my first attempt at this, please let me  know if i did it correct or not.

**Comment by StevenGubkin** [comment]
Ya, looks great.  Thanks for helping out!  Hope you are enjoying the class.

**Comment by jimevart** [comment]
Great fun!

**Comment by jimevart** [comment]
How do I see the update in the activity? I just checked and there is no update button for the page?  Do you have to do an update from git to the website?  Sorry to ask just trying to understand how this system works

Best jim

**Pull request merged**
